esp32:
  board: featheresp32
  framework:
    type: arduino


logger:
  baud_rate: 0
# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solis-Inverter Fallback Hotspot"
    password: ""
  fast_connect: true
  power_save_mode: none


uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus1

modbus_controller:
  - id: solis_inverter
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 300ms

sensor:
  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: ac_watt_instant
    name: "Immediate power generation"
    address: 3004
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 0
    

  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: dc_voltage
    name: "Solar PV Volt"
    address: 3021
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2 
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: dc_current
    name: "Solar PV Current"
    address: 3022
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: ac_voltage
    name: "Grid Voltage"
    address: 3033
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: ac_current
    name: "Grid Current"
    address: 3038
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0
    filters:
      - multiply: 0.10

  
  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: ac_frequency
    name: "Grid Frequency"
    address: 3042
    unit_of_measurement: "Hz"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01


  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: inverter_temp
    name: "Inverter Temperature"
    address: 3041
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1


  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: total_generated_solis
    name: "Total generated since Install"
    address: 3008
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 0



  - platform: modbus_controller
    modbus_controller_id: solis_inverter
    id: today_generated_solis
    name: "Generated Today"
    address: 3014
    unit_of_measurement: "kWh"
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1